export const payments = [
  {
    id: "728ed52f",
    amount: "-200.00 USD",
    method: "Credit Card",
    card: "**** 6829",
    status: "Successful",
    sentTo: "Isagi Yoichi",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    date: "Aug 28, 2024 3:40 PM",
  },
  {
    id: "489e1d42",
    amount: "-200.00 USD",
    method: "Credit Card",
    card: "**** 6829",
    status: "Successful",
    sentTo: "Isagi Yoichi",
    avatar: "https://randomuser.me/api/portraits/men/2.jpg",
    date: "Aug 28, 2024 3:40 PM",
  },
  {
    id: "a1234bcd",
    amount: "-200.00 USD",
    method: "Credit Card",
    card: "**** 6829",
    status: "Successful",
    sentTo: "Isagi Yoichi",
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
    date: "Aug 28, 2024 3:40 PM",
  },
  {
    id: "b5678efg",
    amount: "-200.00 USD",
    method: "Credit Card",
    card: "**** 6829",
    status: "Failed",
    sentTo: "Isagi Yoichi",
    avatar: "https://randomuser.me/api/portraits/men/4.jpg",
    date: "Aug 28, 2024 3:40 PM",
  },
  {
    id: "c9101hij",
    amount: "-200.00 USD",
    method: "Credit Card",
    card: "**** 6829",
    status: "Successful",
    sentTo: "Isagi Yoichi",
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
    date: "Aug 28, 2024 3:40 PM",
  },
  {
    id: "d1121klm",
    amount: "-200.00 USD",
    method: "Credit Card",
    card: "**** 6829",
    status: "Successful",
    sentTo: "Isagi Yoichi",
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
    date: "Aug 28, 2024 3:40 PM",
  },
];
